security:
    providers: { app_user_provider: { entity: { class: App\Entity\User, property: username } } }
    firewalls: { dev: { pattern: ^/(_(profiler|wdt)|css|images|js)/, security: false }, main: { lazy: true, provider: app_user_provider, guard: { authenticators: [App\Security\AppAuthenticator] } } }
    access_control: null
    encoders: { App\Entity\User: { algorithm: auto } }
    enable_authenticator_manager: true
