<?php

namespace App\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM and Glorious Websites Builder. Add your own custom
 * repository methods below.
 */
class Entity10Repository extends \Doctrine\ORM\EntityRepository
{
}